"""
main.py

The "Brain" Microservice Server.
This FastAPI server exposes two endpoints for the Node.js backend ("The Boss") to call.
It handles data validation, routes the data into the LangGraph state machines, 
and returns the AI's JSON output.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Import your compiled LangGraph apps
# Make sure the variable names match what you called them at the bottom of your files!
# Tell main.py to look inside the "agents" folder, then the specific files
from agents.agents import app as evaluation_graph
from agents.teacher_upload import upload_app as teacher_upload

# Initialize the server
app = FastAPI(title="AISS AES - AI Evaluation Microservice")

# Allow CORS (Useful if you ever want to test directly from a frontend, 
# though your Node.js server will usually be the one making the calls).
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==========================================
# Pydantic Schemas (Data Validation)
# ==========================================
class TeacherUploadRequest(BaseModel):
    raw_input: str      # URL to the Image/PDF
    content_type: str   # "notes" or "answer_key"
    subject: str        # e.g., "biology"
    exam_id: str        # e.g., "midterm_2024_v3"
    namespace: str      # e.g., "NIT_Raipur"
    question_no: int    # e.g., 1

class StudentEvaluateRequest(BaseModel):
    raw_input: str      # URL to the student's handwritten Image/PDF
    question: str       # The actual question text
    exam_id: str        # e.g., "midterm_2024_v3"
    namespace: str      # e.g., "NIT_Raipur"
    question_no: int    # e.g., 1


# ==========================================
# API Routes
# ==========================================

@app.get("/")
def health_check():
    """Simple route to check if the Python server is alive."""
    return {"status": "online", "message": "AI Brain is listening."}


@app.post("/api/teacher/upload")
async def upload_teacher_data(request: TeacherUploadRequest):
    """
    ETL Route: Processes Teacher Notes/Keys and stores them in Pinecone.
    """
    try:
        # Convert the incoming JSON into the LangGraph state dictionary
        initial_state = request.dict()
        
        # Invoke the Teacher Upload Graph
        final_state = teacher_upload_graph.invoke(initial_state)
        
        return {
            "status": "success",
            "message": final_state.get("upload_status", "Upload complete.")
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/student/evaluate")
async def evaluate_student(request: StudentEvaluateRequest):
    """
    Agentic Route: Evaluates a student's answer using the AI grading loop.
    """
    try:
        # Convert the incoming JSON into the LangGraph state dictionary
        initial_state = request.dict()
        
        # Invoke the Student Evaluation Graph
        final_state = evaluation_graph.invoke(initial_state)
        
        # Extract the final feedback generated by the LLM
        evaluation_result = final_state.get("evaluation")
        
        if not evaluation_result:
            raise ValueError("Evaluation Agent failed to generate feedback.")

        return {
            "status": "success",
            "exam_id": request.exam_id,
            "evaluation": evaluation_result
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))